# Generated by Django 4.1.1 on 2022-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("andromeda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="about",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
            options={"verbose_name": "About", "verbose_name_plural": "About",},
        ),
        migrations.CreateModel(
            name="ContactProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("number", models.CharField(max_length=9, verbose_name="Number")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Contact Profile",
                "verbose_name_plural": "Contact Profiles",
                "ordering": ["timestamp"],
            },
        ),
    ]
