# Generated by Django 4.1.1 on 2022-09-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("andromeda", "0004_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(name="about",),
        migrations.DeleteModel(name="ContactProfile",),
        migrations.DeleteModel(name="UserProfile",),
    ]
