# Generated by Django 4.1.1 on 2022-09-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("andromeda", "0007_blog_review_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Review Profiles",
            },
        ),
    ]
