# Generated by Django 4.1.1 on 2022-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("andromeda", "0008_alter_review_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Upload review",
                "verbose_name_plural": "Upload reviews",
            },
        ),
    ]
