# Generated by Django 4.1.1 on 2022-09-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("andromeda", "0009_uploadreview"),
    ]

    operations = [
        migrations.DeleteModel(name="UploadReview",),
    ]
