# Generated by Django 4.1.1 on 2022-09-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("andromeda", "0011_contactprofile"),
    ]

    operations = [
        migrations.DeleteModel(name="ContactProfile",),
    ]
