# Generated by Django 4.1.1 on 2022-09-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("andromeda", "0015_contactprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactprofile",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
