# Generated by Django 4.1.1 on 2022-09-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andromeda', '0016_alter_contactprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactProfile',
        ),
    ]
